# Generated by Django 2.2 on 2023-09-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategoris',
                'ordering': ['nama_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun_terbit', models.PositiveIntegerField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Kategori')),
            ],
        ),
    ]
